# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abb5432d731182c1094d0ac34bfc4c4a23bd01f17137b159edc7da2cdaaef2873396fcecbe05d0e83e9e83ef3bd317980bf8ce6812c6a9eeb2e30fa69ec57e85

test:
  secret_key_base: ba26f00ffde3103d73e86de4f3b0d45bc02af2c096080b45732442bbfdbc06393ee59290831f53cc3b50098d5a20e98b31f28c5dd80599efb2ca19c158cf14b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
